language: python
python:
  - "3.3"
install:
  - time pip install -r pyparsing-2.0.1

before_script:
  - cd ..
  - git clone https://git01.codeplex.com/z3 -b unstable
  - python3 scripts/mk_make.py
  - cd build
  - make

script:
  - bin/sh auto_group/runTestCases.sh
