language: python
python:
  - "3.3"
install:
  - pip install -r pyparsing

before_script
  - cd ..
  - git clone https://git01.codeplex.com/z3 -b unstable
  - python3 scripts/mk_make.py
  - cd build
  - make
