language: python
python:
  - "3.3"
install:
  - pip install http://cheeseshop.python.org/packages/source/p/pyparsing/pyparsing-2.0.1.tar.gz

before_script:
  - cd ..
  - git clone git clone git@github.com:Z3Prover/z3.git
  - python3 scripts/mk_make.py
  - cd build
  - make

script:
  - bin/sh auto_group/unitTestAGPlus-ENC.sh
